version: '2'
services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer/data:/data

  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    env_file: ./services/nodered/nodered.env
    ports:
      - 1880:1880
    volumes:
      - ./volumes/nodered/data:/data

  influxdb:
    container_name: influxdb
    image: "influxdb:latest"
    restart: unless-stopped
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    env_file:
      - ./services/influxdb/influxdb.env
    volumes:
      - ./volumes/influxdb/data:/var/lib/influxdb
      - ./backups/influxdb/db:/var/lib/influxdb/backup

  grafana:
    container_name: grafana
    image: grafana/grafana:6.3.6
    restart: unless-stopped
    user: "0"
    ports:
      - 3000:3000
    env_file:
      - ./services/grafana/grafana.env
    volumes:
      - ./volumes/grafana/data:/var/lib/grafana
      - ./volumes/grafana/log:/var/log/grafana

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      #- UMASK_SET=022 #optional
    volumes:
      - ./volumes/plex/config:/config
      - /media/data/TV:/media/TV
      - /media/data/Movies:/media/Movies
      - ./volumes/plex/transcode:/transcode
    restart: unless-stopped

  zerotierone:
    image: ugeek/zerotier:arm
    container_name: zerotierone
    network_mode: host
    ports:
      - 3443:3443
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    volumes:
      - ./volumes/zerotierone:/var/lib/zerotier-one
    devices:
      - /dev/net/tun
    restart: unless-stopped

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - 9321:80
    volumes:
      - /media/volumes/nextcloud/html:/var/www/html
    restart: unless-stopped
    depends_on: 
      - nextcloud_db

  nextcloud_db:
    image: linuxserver/mariadb
    container_name: nextcloud_db
    volumes:
      - /media/volumes/nextcloud/db:/config
    environment:
      - MYSQL_ROOT_PASSWORD=stronger_password
      - MYSQL_PASSWORD=strong_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./volumes/homeassistant:/config
    devices:
      - /dev/ttyUSB0:/dev/zwave
      - /dev/ttyUSB1:/dev/zigbee
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 8123:8123
    restart: always
    network_mode: host
