resources:
  - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
    type: module
title: Home - Lakeside
views:
  - title: Control
    path: control
    theme: dark
    cards:
      - type: iframe
        url: https://embed.windy.com/embed2.html?lat=37.754&lon=-122.257&detailLat=37.803&detailLon=-122.257&width=650&height=450&zoom=11&level=surface&overlay=wind&product=ecmwf&menu=&message=&marker=&calendar=now&pressure=&type=map&location=coordinates&detail=true&metricWind=default&metricTemp=default&radarRange=-1
        aspect_ratio: 75%
      - title: Bedroom
        type: entities
        entities:
          - entity: group.bedroom_lights
          - name: Joes Light
            type: custom:slider-entity-row
            entity: light.joes_light
            toggle: true
          - name: Shirley's Light
            type: custom:slider-entity-row
            entity: light.shirleys_light
            toggle: true
          - entity: light.led_string_lights
      - title: Dining Room
        type: entities
        entities:
          - name: Dining Room Light
            type: custom:slider-entity-row
            entity: light.dining_room_light
            toggle: true
          - entity: switch.occulus
      - title: Kitchen
        type: entities
        entities:
          - name: Under Cabinet Light
            type: custom:slider-entity-row
            entity: light.kitchen_cabinet_light
            toggle: true
          - entity: scene.cooking_in_kitchen
          - entity: scene.spring_blossom_in_kitchen
          - entity: scene.tropical_twilight_in_kitchen
          - entity: scene.savanna_sunset_in_kitchen
          - entity: scene.arctic_aurora_in_kitchen
          - entity: scene.dimmed_in_kitchen
          - entity: scene.nightlight_in_kitchen
      - title: Living Room
        type: entities
        entities:
          - entity: remote.living_room
          - name: Main Lamp
            type: custom:slider-entity-row
            entity: light.main_living_room_lamp
            toggle: true
          - name: Couch Light
            type: custom:slider-entity-row
            entity: light.couch_light
            toggle: true
          - name: Couch RGB
            type: custom:slider-entity-row
            entity: light.couch_rgb
            toggle: true
          - name: TV RGB
            type: custom:slider-entity-row
            entity: light.tv_lamp
            toggle: true
          - entity: light.christmas_tree_light
          - entity: group.living_room_rgb 
          - entity: scene.bright_in_living_room
          - entity: scene.spring_blossom_in_living_room
          - entity: scene.tropical_twilight_in_living_room
          - entity: scene.savanna_sunset_in_living_room
          - entity: scene.arctic_aurora_in_living_room
          - entity: scene.dimmed_in_living_room
          - entity: scene.nightlight_in_living_room
      - title: Bathroom
        type: entities
        entities:
          - name: Main Bathroom Light
            type: custom:slider-entity-row
            entity: light.main_bathroom_light
            toggle: true
      - title: Desk LED
        type: entities
        entities: 
          - name: Desk LED
            type: custom:slider-entity-row
            entity: light.desk_led
            toggle: true
          - entity: scene.working_at_desk
          - entity: scene.spring_blossom_at_desk
          - entity: scene.tropical_twilight_at_desk
          - entity: scene.savanna_sunset_at_desk
          - entity: scene.arctic_aurora_at_desk
          - entity: scene.dimmed_at_desk
          - entity: scene.nightlight_at_desk
  - title: Overview
    path: default_view
    badges:
      - entity: binary_sensor.updater
      - entity: sun.sun
    cards:
      - entities:
          - entity: light.kitchen_cabinet_light
            name: Cabinet Light
          - entity: light.dining_room_light
          - entity: switch.occulus
          - entity: light.couch_light
          - entity: light.inovelli
          - entity: light.christmas_tree_light
          - entity: light.joes_light
          - entity: light.shirleys_light
          - entity: light.led_string_lights
        title: All Lights
        type: entities
      - entity: weather.home_lakeside
        type: weather-forecast
      - entity: light.dining_room_light
        type: light
      - entity: light.inovelli
        type: light
      - entity: light.joes_light
        type: light
      - entity: light.shirleys_light
        type: light
